### ISSUE TITLE
Separate services in different repos

### ISSUE THREAD

**Issue by demiurgosoft** [demiurgosoft/maelstrom#87]
make funny stuff with git submodules, each repository for each microservice

**Comment by demiurgosoft** [comment]
something like `git submodule add URL-del-repo`

**Comment by iblancasa** [comment]
Use titles more descriptives please

**Comment by demiurgosoft** [comment]
@iblancasa happy now?

**Comment by iblancasa** [comment]
Yeah!

**Comment by demiurgosoft** [comment]
use submodules now on metarepo maelstrom

**Comment by iblancasa** [comment]
You have to add the submodules to the metarepo

```git submodule add [URL]```

**Comment by demiurgosoft** [comment]
yep, working on it

**Comment by iblancasa** [comment]
Close!

**Comment by demiurgosoft** [comment]
proxy still doing crazy stuff, but yeah, close
